baseURL: "https://plarge.github.io/"

languageCode: "en-us"
title: "plarge.github.io"
relativeURLs: true
canonifyURLs: true

resourceDir: ../resources

module:
  imports:
  - path: github.com/hugo-toha/toha
  
# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"

# Site parameters
params:
