baseURL: "https://plarge.github.io/"
languageCode: "en-us"
title: "plarge.github.io"
relativeURLs: true
canonifyURLs: true

resourceDir: ../resources

module:
  imports:
  - path: github.com/hugo-toha/toha
  
params:

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
