baseURL: "https://plarge.github.io/"
languageCode: "en-us"
title: "plarge.github.io"
#theme: "hugo-theme-learn"
RelativeURLs: true
CanonifyURLs: true

module:
  imports:
  - path: github.com/matcornic/hugo-theme-learn

params:
  pygmentsCodeFences: true
  pygmentsStyle: "monokai"
  editURL: ""
  author: "plarge"
  description: "Documentation for plarge.github.io"
  showVisitedLinks: false
  disableSearch: false
  disableAssetsBusting: false
  disableInlineCopyToClipBoard: false
  disableShortcutsTitle: false
  disableLanguageSwitchingButton: false
  disableBreadcrumb: true
  disableNextPrev: false
  ordersectionsby: "weight"
  themeVariant: "green"

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
